# Generated by Django 3.1.2 on 2020-10-11 19:09

from django.db import migrations
from django.contrib.auth import get_user_model
from api.models import Reviewer, Company


def create_users(apps, schema_editor):
    """
    Create some test Users.
    """
    UserModel = get_user_model()

    users = [
        {
            'username': 'admin',
            'password': 'admin',
            'is_staff': True,
            'is_superuser': True
        },
        {
            'username': 'john',
            'password': '123',
        },
        {
            'username': 'mary',
            'password': '321',
        },
        {
            'username': 'carlos',
            'password': '123',
            'self_description': 'I am very nice person!'
        }
    ]
    for data in users:
        user = UserModel.objects.create_user(
            username=data['username'],
            password=data['password'],
            is_staff=data.get('is_staff', False),
            is_superuser=data.get('is_superuser', False)
        )
        Reviewer.objects.create(
            user=user,
            self_description=data.get('self_description')
        )


def create_companies(apps,schema_editor):
    """
    Create some test companies.
    """
    Company.objects.create(name='Cool Car')
    Company.objects.create(name='Cool SocialMedia')
    Company.objects.create(name='Cool App')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
        migrations.RunPython(create_companies),
    ]
